### ISSUE TITLE
Images not loading and throwing errors

### ISSUE THREAD

**Issue by ggroot** [vnbaaij/ImageProcessor.Web.Episerver#23]
Anybody have any idea how to fix this error. Right now Images take a very long time to load and often result in this error. 

System.Web.HttpException (0x80004005): Server cannot append header after HTTP headers have been sent.
   at System.Web.HttpResponse.AppendHeader(String name, String value)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.SetHeaders(HttpContext context, String responseType, String[] dependencyPaths, Int32 maxDays, Nullable`1 statusCode)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.SetHeaders(HttpContext context, Int32 maxDays)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.PostReleaseRequestState(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by vnbaaij** [comment]
Are you using the latest versions? And this is on Azure, right? If so, please check security.config that there is only one EpiserverImageService defined and that that one has the following code:
```
<settings>
        <setting key="OnAzure" value="true"/>
</settings>
```

**Comment by ggroot** [comment]
Thanks Vincent, that was the trick.

**Comment by mikaelhanssonvaltech** [comment]
I get this error while moving a site to DXP. I have checked the setting mentioned above. It works for some images but many time out with the browser console error "net::ERR_SPDY_PROTOCOL_ERROR 200".

In Azure I get the stack trace below. Worth mentioning is that I had to add an assembly binding redirect as ImageProcessor.Web.Episerver.Azure references version  8.5.0.0 of Microsoft.WindowsAzure.Storage and EPiServer.Azure.dll References 9.3.2.0 of that assembly from Episerver.Azure v9.4.5. Any ideas?

System.Web.HttpException:
   at System.Web.HttpResponse.AppendHeader (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.SetHeaders (ImageProcessor.Web, Version=4.12.0.206, Culture=neutral, PublicKeyToken=null)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.SetHeaders (ImageProcessor.Web, Version=4.12.0.206, Culture=neutral, PublicKeyToken=null)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.PostReleaseRequestState (ImageProcessor.Web, Version=4.12.0.206, Culture=neutral, PublicKeyToken=null)
   at System.Web.HttpApplication+SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Web.HttpApplication+<>c__DisplayClass285_0.<ExecuteStepImpl>b__0 (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Web.HttpApplication.ExecuteStepImpl (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Web.HttpApplication.ExecuteStep (System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)

**Comment by vnbaaij** [comment]
The error seems to indicate that there is a general communication problem between the client and the server. It doesn't really point to the ImageProcessor package. Can you try to download a single image by getting the link from the html source and see if that gives an error too? And maybe verify that the file actually exists in the blob storage.

On the assembly binding: I  just uploaded v5.6.3 for the Azure component which now references the WindwsAzure.Storage 9.3.3 package. The binding should then no longer be necessary. According to the dependencies shown on the nuget.episerver.com site 9.3.3 is the version Episerver is referencing as well

**Comment by mikaelhanssonvaltech** [comment]
For instance, I have a menu with something like 30 small images that are being resized and cropped. 23 loads ok, 3 loads halfway and the remaining 4 doesn't load at all. They all behave the same if I just browse to their respective urls, i.e the ones that fails, fail then as well.

Thanks for updating the reference. I'll check it out as soon as it's available.

**Comment by vnbaaij** [comment]
And did you also try in different browsers?

**Comment by vnbaaij** [comment]
It could also be a problem with the specific images. I've seen this happen before

**Comment by mikaelhanssonvaltech** [comment]
Yes, same behavior in Chrome, Safari, Edge & Firefox. I can mention that it works locally with the ImageProcessor.Web.Episerver.FileBlobCache

I will check if the images are the problem.

**Comment by vnbaaij** [comment]
The new version is live on the feed now...

**Comment by mikaelhanssonvaltech** [comment]
New info, it works with the internal hostname, [client_specific_app_id].dxcloud.episerver.net, but not on the "nice" hostname, integration.[client_company].com. I'll take it further with their support to see if they have a clue what might cause this.

**Comment by mikaelhanssonvaltech** [comment]
The difference is that the first one doesn't have CDN enabled, whereas the other one has CDN enabled.

**Comment by vnbaaij** [comment]
Hmm, a bell is starting to ring softly. Can you change the StreamCachedImage setting in the cache.config (<setting` key="StreamCachedImage" value="true"/>) file to see if that makes a difference?

**Comment by mikaelhanssonvaltech** [comment]
I set it to false instead and purged the CDN cache. Same problem.

**Comment by vnbaaij** [comment]
I'm afraid I'm out of options then. I don't have a DXC environment to experiment with. Maybe you can ask a question on the forum on World to see if someone has a comparable setup and what their settings are.

**Comment by mikaelhanssonvaltech** [comment]
Ok, I understand. Thank you for trying to help out!

**Comment by ggroot** [comment]
Make sure the resizer is not using the FileBlobCache but uses AzureBlobCache in the DXC. DXC has a limited disk space.

The imageProcessor section in the DXC web.config should look something like this:

```
  <imageProcessor>
    <caching currentCache="EpiserverAzureBlobCache">
      <caches>
        <cache name="EpiserverAzureBlobCache" type="ImageProcessor.Web.Episerver.Azure.AzureBlobCache, ImageProcessor.Web.Episerver.Azure" maxDays="365">
          <settings>
            <setting key="StreamCachedImage" value="true"/>
            <setting key="CDNTimeout" value="1000"/>
          </settings>
        </cache>
      </caches>
    </caching>
    <security>
      <services>
        <service name="EpiserverImageService" type="ImageProcessor.Web.Episerver.ImageService, ImageProcessor.Web.Episerver">
          <settings>
            <setting key="OnAzure" value="true"/>
          </settings>
        </service>
      </services>
    </security>
    <processing configSource="config\imageprocessor\processing.config"/>
  </imageProcessor>
```
