### ISSUE TITLE
Frequently occurring error: Server cannot append header after HTTP headers have been sent.

### ISSUE THREAD

**Issue by bnitt** [vnbaaij/ImageProcessor.Web.Episerver#53]
System.Web.HttpException (0x80004005): Server cannot append header after HTTP headers have been sent.
   at System.Web.HttpResponse.AppendHeader(String name, String value)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.SetHeaders(HttpContext context, String responseType, String[] dependencyPaths, Int32 maxDays, Nullable`1 statusCode)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.SetHeaders(HttpContext context, Int32 maxDays)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.PostReleaseRequestState(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.<>c__DisplayClass285_0.b__0()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)",

**Comment by vnbaaij** [comment]
This is (almost certainly) a configuration error. Need more details if you want me took take a deeper look at this.
