### ISSUE TITLE
Unhandled HttpException in ImageProcessor.Web.Episerver.FileBlobCache.RewritePath

### ISSUE THREAD

**Issue by ErikJJonsson** [vnbaaij/ImageProcessor.Web.Episerver#56]
Hi, 
We are using ImageProcessor.Web.Episerver" version="5.6.5.15612" and are getting a lot of errors like this:

System.Web.HttpException (0x800704CD): The remote host closed the connection. The error code is 0x800704CD.
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
   at System.Web.HttpResponse.End()
   at ImageProcessor.Web.Episerver.FileBlobCache.RewritePath(HttpContext context)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__31.MoveNext()
   
A try-catch exists in RewritePath() which catches ThreadAbortException but HttpException is not handled.
Could that be added?

**Comment by vnbaaij** [comment]
I've added a `catch (HttpException)` in v5.7.0

**Comment by ErikJJonsson** [comment]
Thank you!
Looks promising.

**Comment by vnbaaij** [comment]
I've submitted the packages to the feed, so they should be available soon.

**Comment by ErikJJonsson** [comment]
It just turned up. :-)
Keep up the good job!
